language: node_js
node_js:
- node
before_install: yarn global add greenkeeper-lockfile@1
install: yarn
before_script: greenkeeper-lockfile-update
script: yarn build:dev
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: mats.pfeiffer@googlemail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
cache:
  yarn: true
notifications:
  email:
    on_success: never
    on_failure: always
